name: Lint source code

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        python -m pip install --upgrade ruff
    - name: Lint with Ruff
      run:  ruff .  --diff --format github

  flake8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        python -m pip install --upgrade flake8
    - name: Lint with Ruff
      run:  flake8 .

  black:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        python -m pip install --upgrade black
    - name: Lint with Ruff
      run:  black .  --diff --color

  isort:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        python -m pip install --upgrade isort
    - name: Lint with Ruff
      run:  isort .  --diff --color
