name: CI

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: Python ${{ matrix.python }}, Sphinx ${{ matrix.sphinx }}
    strategy:
      fail-fast: false
      matrix:
        python:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12-dev"
        sphinx:
        - "4"
        - "5"
        - "6"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      if: "!endsWith(matrix.python, '-dev')"
      with:
        python-version: ${{ matrix.python }}
    - name: Set up Python ${{ matrix.python }} (deadsnakes)
      uses: deadsnakes/action@v2.1.1
      if: "endsWith(matrix.python, '-dev')"
      with:
        python-version: ${{ matrix.python }}
    - name: Check Python version
      run: python --version
    - name: Install Sphinx
      run: |
        python -m pip install -U pip
        python -m pip install -U "releases==1.6.3" six
        python -m pip install -U "sphinx==${{ matrix.sphinx }}.*"
        python -m pip install .
    - name: Run Sphinx
      run: sphinx-build ./docs ./build

  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - name: Install Sphinx
      run: |
        python -m pip install -U pip
        python -m pip install "releases==1.6.3" six
        python -m pip install -U sphinx
        python -m pip install .
    - name: Run Sphinx
      run: sphinx-build ./docs ./build
